spring:
  application:
    name: bills
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      username: secret
      password: secret
      fail-fast: true


